adds missing lerna commands from lernajs.io
lerna/website pull request #60
Opened 2018-10-08 20:06 UTC by dakebl

Answering the issue I raised about missing commands (#59)

2018-12-11 05:44 UTC, doug-wade requested changes

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +        <section class="command" id="command-ls">
id="command-add"

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +          <h3><a href="#command-ls">
href="#command-add"

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +                # Install module-1 to module-2 <br/>
Add module-1 as a dependency of module-2 (install is one-time, adding as a dependency is permanent)

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +                # Install module-1 in all modules except module-1 <br/>
This one and the one following it seem identical at first glance.  Please add some disambiguation.

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +        <section class="command" id="command-ls">
id="command-version"

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +          <h3><a href="#command-ls">
href="#command-version"

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +            <code>lerna version patch # semver keyword </code><br/>
\# semver keyword, as enumerated below

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +          <h3><a href="#command-ls">
href="#command-exec"

2018-12-11 05:44 UTC, doug-wade commented on index.html
> +        <section class="command" id="command-ls">
id="command-exec"

2018-12-11 05:44 UTC, doug-wade commented on index.html
>          <section class="command" id="command-ls">
This seems like some mistaken copy-pasta

2022-06-15 14:15 UTC, JamesHenry commented
Hi @dakebl 👋 

Thanks a lot for taking the initiative to contribute this PR!

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

We have just pushed out a new version of the website, which we will continue to iterate on, we hope you like it and find it useful!

Feel free to open a new issue on here if you spot anything that needs fixing or improving, but for now this PR is no longer applicable to the current site so we are closing it.

Many thanks 🙏

2022-06-15 14:15 UTC, closed without merging